export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  profile: '/profile',
  about: '/about',
  contact: '/contact',
  verifyEmailSuccess: '/verify-email/success',
  verifyEmailFailed: '/verify-email/failed',
  accountRequest: '/account-request',
  download: '/download',
  error401: '/401',
  dashboard: '/dashboard',
  table: '/table',
  eventTable: '/event-table',
  ppeTable: '/ppe-table',
  smokeSampleTable: '/smoke-sample-table',
  notFound: '*',
  legacyVerify: '/verify',
  legacyFailedVerification: '/failedVerification',
  legacyTablePage: '/tablePage',
} as const
